# Generated by Django 5.1.2 on 2024-10-09 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Transaction_date',
            new_name='transaction_date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactiontype',
            new_name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='destination',
        ),
        migrations.AddField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receive_transaction', to='payment.paymentaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transaction', to='payment.paymentaccount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='account_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
